import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, RADIUS, SHADOW } from './theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  screen: { flex: 1 },
  content: { flex: 1 },
  header: { paddingHorizontal: SPACING.md, paddingTop: Platform.OS === 'android' ? 40 : 10, paddingBottom: SPACING.md, borderBottomWidth: 0 },
  headerSimple: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: SPACING.md, borderBottomWidth: 0, paddingTop: Platform.OS === 'android' ? 40 : 10 },
  logoText: { fontSize: 26, fontWeight: '800', letterSpacing: -0.5 },
  headerTitle: { fontSize: 18, fontWeight: '700' },
  headerIconContainer: { padding: 8, borderRadius: RADIUS.full },
  searchBar: { flexDirection: 'row', alignItems: 'center', borderRadius: RADIUS.lg, paddingHorizontal: SPACING.md, height: 48 },
  searchInput: { flex: 1, marginLeft: 10, fontSize: 16 },
  suggestionsDropdown: {
    position: 'absolute',
    top: 54,
    left: 0,
    right: 0,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    overflow: 'hidden',
    ...SHADOW.md,
    zIndex: 9999,
    elevation: Platform.OS === 'android' ? 20 : undefined,
  },
  dropdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  dropdownHeaderText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  clearHistoryBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  historyDeleteBtn: {
    padding: 6,
    borderRadius: RADIUS.full,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  suggestionIconBg: {
    width: 26,
    height: 26,
    borderRadius: RADIUS.full,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  suggestionText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  categoryChip: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: RADIUS.full, marginRight: SPACING.sm, borderWidth: 1 },
  categoryText: { fontWeight: '600', fontSize: 13 },
  locationChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.full, borderWidth: 1, gap: 5 },
  locationChipText: { fontSize: 12 },
  card: { borderRadius: RADIUS.lg, marginBottom: SPACING.md, overflow: 'hidden', ...SHADOW.sm, borderWidth: 1 },
  cardImageContainer: { height: 160, position: 'relative' },
  cardImage: { width: '100%', height: '100%' },
  cardBadgeContainer: { position: 'absolute', top: 8, left: 8, flexDirection: 'row' },
  categoryBadge: { backgroundColor: 'rgba(0,0,0,0.6)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: RADIUS.sm },
  categoryBadgeText: { color: 'white', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  heartBtn: { position: 'absolute', top: 8, right: 8, borderRadius: RADIUS.full, padding: 6, ...SHADOW.sm, borderWidth: 1, borderColor: 'rgba(0,0,0,0.1)' },
  cardContent: { padding: SPACING.md },
  cardTitle: { fontSize: 15, fontWeight: '600', marginBottom: 4 },
  cardPrice: { fontSize: 18, fontWeight: '800' },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  sellerName: { fontSize: 12, maxWidth: '80%' },
  imageCount: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  imageCountText: { fontSize: 10, marginLeft: 4, fontWeight: '600' },
  detailHeader: { position: 'absolute', top: 0, left: 0, right: 0, flexDirection: 'row', justifyContent: 'space-between', padding: SPACING.md, zIndex: 10, paddingTop: 50 },
  floatingBackBtn: { position: 'absolute', top: 50, left: 20, padding: 10, borderRadius: RADIUS.full, ...SHADOW.md },
  floatingHeartBtn: { position: 'absolute', top: 50, right: 20, padding: 10, borderRadius: RADIUS.full, ...SHADOW.md },
  floatingShareBtn: { position: 'absolute', top: 50, right: 72, padding: 10, borderRadius: RADIUS.full, ...SHADOW.md },
  floatingReportBtn: { position: 'absolute', top: 50, right: 124, padding: 10, borderRadius: RADIUS.full, ...SHADOW.md },
  contactActionsRow: { flexDirection: 'row', gap: 12, marginVertical: 14 },
  contactActionBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, paddingHorizontal: 16, borderRadius: RADIUS.md, borderWidth: 1, gap: 8 },
  contactActionText: { fontSize: 14, fontWeight: '600' },
  soldBanner: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: RADIUS.md, borderWidth: 1, marginBottom: 14, gap: 8 },
  soldBannerText: { fontSize: 14, fontWeight: '700' },
  soldBadgeOverlay: { position: 'absolute', top: 8, left: 8, backgroundColor: '#EF4444', paddingHorizontal: 8, paddingVertical: 4, borderRadius: RADIUS.sm, zIndex: 5 },
  soldBadgeText: { color: 'white', fontSize: 10, fontWeight: '800', letterSpacing: 0.5 },
  similarCard: { width: 140, borderRadius: RADIUS.md, borderWidth: 1, overflow: 'hidden', position: 'relative' },
  similarThumb: { width: '100%', height: 100, backgroundColor: '#e5e7eb' },
  similarTitle: { fontSize: 13, fontWeight: '600', marginBottom: 2 },
  similarPrice: { fontSize: 14, fontWeight: '700' },
  detailContainer: { borderTopLeftRadius: 24, borderTopRightRadius: 24, marginTop: -20, padding: SPACING.lg, minHeight: 500 },
  detailTitle: { fontSize: 24, fontWeight: '800', marginBottom: 8 },
  detailPrice: { fontSize: 24, fontWeight: '800' },
  tag: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  tagText: { fontSize: 12, fontWeight: '600' },
  sellerRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, marginBottom: 16 },
  sellerAvatar: { width: 44, height: 44, borderRadius: 22 },
  sectionTitle: { fontSize: 18, fontWeight: '700', marginBottom: 8 },
  detailDesc: { fontSize: 16, lineHeight: 24 },
  bottomActionContainer: { position: 'absolute', bottom: 0, width: '100%', padding: SPACING.lg, borderTopWidth: 1, paddingBottom: 40 },
  inputContainer: { marginBottom: 16, flexDirection: 'row', alignItems: 'center', borderRadius: RADIUS.md, paddingHorizontal: SPACING.md, height: 50 },
  modernInput: { flex: 1, height: '100%', fontSize: 16 },
  sectionLabel: { fontSize: 16, fontWeight: '700', marginBottom: 12 },
  addPhotoBtn: { width: 80, height: 80, borderRadius: RADIUS.md, borderStyle: 'dashed', borderWidth: 1, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  addPhotoText: { fontSize: 12, marginTop: 4 },
  photoThumbContainer: { position: 'relative', marginRight: 10 },
  photoThumb: { width: 80, height: 80, borderRadius: RADIUS.md },
  removePhotoBtn: { position: 'absolute', top: -5, right: -5, backgroundColor: COLORS.danger, borderRadius: 10, padding: 4 },
  primaryBtn: { paddingVertical: 16, borderRadius: RADIUS.xl, alignItems: 'center', justifyContent: 'center', ...SHADOW.md },
  primaryBtnText: { color: 'white', fontSize: 16, fontWeight: '700' },
  secondaryBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: RADIUS.full, borderWidth: 1 },
  secondaryBtnText: { fontWeight: '600', fontSize: 13 },
  chatListItem: { flexDirection: 'row', padding: SPACING.md, marginBottom: 1, borderBottomWidth: 1 },
  avatarContainer: { position: 'relative' },
  avatar: { width: 56, height: 56, borderRadius: 28 },
  avatarPlaceholder: { width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center' },
  avatarInitial: { color: 'white', fontSize: 24, fontWeight: 'bold' },
  onlineBadge: { position: 'absolute', bottom: 2, right: 2, width: 14, height: 14, borderRadius: 7, borderWidth: 2 },
  chatContent: { flex: 1, marginLeft: 16, justifyContent: 'center' },
  chatHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  chatName: { fontSize: 16, fontWeight: '700' },
  chatTime: { fontSize: 12 },
  chatListingTitle: { fontSize: 12, fontWeight: '600', marginBottom: 2 },
  chatMessageRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  chatLastMessage: { fontSize: 14, flex: 1, marginRight: 10 },
  chatUnreadText: { fontWeight: '600' },
  unreadCountBadge: { borderRadius: 10, minWidth: 20, height: 20, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 6 },
  unreadCountText: { color: 'white', fontSize: 10, fontWeight: 'bold' },
  chatHeader: { flexDirection: 'row', alignItems: 'center', padding: SPACING.md, borderBottomWidth: 1 },
  backBtn: { marginRight: 16 },
  profileHeader: { alignItems: 'center', padding: SPACING.xl },
  profileAvatarContainer: { position: 'relative', marginBottom: 16 },
  profileAvatar: { width: 100, height: 100, borderRadius: 50 },
  editAvatarBadge: { position: 'absolute', bottom: 0, right: 0, padding: 8, borderRadius: 20, borderWidth: 4 },
  profileName: { fontSize: 22, fontWeight: '800', marginBottom: 4 },
  profileEmail: { fontSize: 14 },
  profileTabs: { flexDirection: 'row', paddingHorizontal: SPACING.md, borderBottomWidth: 1 },
  profileTabItem: { flex: 1, paddingVertical: 16, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  profileTabText: { fontWeight: '600' },
  listItemRow: { flexDirection: 'row', padding: SPACING.md, marginBottom: SPACING.sm, borderRadius: RADIUS.md, alignItems: 'center' },
  listThumb: { width: 60, height: 60, borderRadius: 8, marginRight: 12 },
  listTitle: { fontSize: 16, fontWeight: '600' },
  listPrice: { fontSize: 14, fontWeight: '700' },
  iconBtn: { padding: 8, borderRadius: 8, marginLeft: 8 },
  emptyState: { alignItems: 'center', marginTop: 50 },
  emptyText: { fontSize: 16 },
  tabBar: { flexDirection: 'row', borderTopWidth: 0, paddingBottom: Platform.OS === 'ios' ? 0 : 4, paddingTop: 8, height: 60, justifyContent: 'space-around', alignItems: 'center' },
  tabItem: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  tabLabel: { fontSize: 10, marginTop: 4, fontWeight: '600' },
  tabBadge: { position: 'absolute', top: -4, right: 4, borderRadius: 6, minWidth: 16, height: 16, justifyContent: 'center', alignItems: 'center', borderWidth: 2 },
  tabBadgeText: { color: 'white', fontSize: 9, fontWeight: 'bold' },
  imagePlaceholder: { width: '100%', height: 350, alignItems: 'center', justifyContent: 'center' },
  modalContainer: { flex: 1, backgroundColor: 'black', justifyContent: 'center', alignItems: 'center' },
  modalImage: { width: '100%', height: '100%' },
  modalCloseBtn: { position: 'absolute', top: 50, right: 20, zIndex: 20 },
  navBtnLeft: { position: 'absolute', left: 20, top: '50%', zIndex: 10, marginTop: -24 },
  navBtnRight: { position: 'absolute', right: 20, top: '50%', zIndex: 10, marginTop: -24 },
  modalCounter: { position: 'absolute', bottom: 50, backgroundColor: 'rgba(0,0,0,0.7)', padding: 8, borderRadius: 8 }
});
