/* ====================================================================
   NearBuy - Complete Supabase Security Hardening & RLS Script
   Ekzekutoni këtë script në Supabase Dashboard -> SQL Editor
   ==================================================================== */

/* 1. SIGURIMI I TABELAVE DHE KOLONAVE BAZË */
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS display_name TEXT;
ALTER TABLE IF EXISTS profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;

ALTER TABLE IF EXISTS listings ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS listings ADD COLUMN IF NOT EXISTS condition TEXT DEFAULT 'used';

ALTER TABLE IF EXISTS messages ADD COLUMN IF NOT EXISTS buyer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_messages_buyer_id ON messages(buyer_id);

/* Tabela për raportimet e shpalljeve */
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT REFERENCES listings(id) ON DELETE CASCADE,
  reporter_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

/* Tabela për vlerësimet e shitësve */
CREATE TABLE IF NOT EXISTS seller_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID NOT NULL,
  reviewer_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewer_name TEXT,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

/* ====================================================================
   2. AKTIVIZIMI I ROW LEVEL SECURITY (RLS) NË TË GJITHA TABELAT
   ==================================================================== */
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE seller_reviews ENABLE ROW LEVEL SECURITY;

/* ====================================================================
   3. PASTRIMI I POLIKAVE TË VJETRA (NËSE EKZISTOJNË)
   ==================================================================== */
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
DROP POLICY IF EXISTS "Users can delete own profile" ON profiles;

DROP POLICY IF EXISTS "Listings are viewable by everyone" ON listings;
DROP POLICY IF EXISTS "Users can create listings" ON listings;
DROP POLICY IF EXISTS "Users can update own listings" ON listings;
DROP POLICY IF EXISTS "Users can delete own listings" ON listings;

DROP POLICY IF EXISTS "Users can view their own messages" ON messages;
DROP POLICY IF EXISTS "Users can insert messages" ON messages;
DROP POLICY IF EXISTS "Users can delete own messages" ON messages;
DROP POLICY IF EXISTS "Users can update received messages" ON messages;

DROP POLICY IF EXISTS "Users can view own favorites" ON favorites;
DROP POLICY IF EXISTS "Users can insert own favorites" ON favorites;
DROP POLICY IF EXISTS "Users can delete own favorites" ON favorites;

DROP POLICY IF EXISTS "Allow authenticated to insert reports" ON reports;
DROP POLICY IF EXISTS "Allow anon to insert reports" ON reports;
DROP POLICY IF EXISTS "Allow all to submit reports" ON reports;
DROP POLICY IF EXISTS "Only admins view reports" ON reports;

DROP POLICY IF EXISTS "Allow all to view reviews" ON seller_reviews;
DROP POLICY IF EXISTS "Allow authenticated to insert reviews" ON seller_reviews;
DROP POLICY IF EXISTS "Users can update own reviews" ON seller_reviews;

/* ====================================================================
   4. KRIJIMI I POLIKAVE STRIKTE TË SIGURISË (RLS POLICIES)
   ==================================================================== */

/* --- A. PROFILES --- */
/* Kushdo mund të lexojë profilet publike */
CREATE POLICY "Public profiles are viewable by everyone"
ON profiles FOR SELECT
USING (true);

/* Vetëm përdoruesi i kyçur mund të krijojë profilin e tij */
CREATE POLICY "Users can insert their own profile"
ON profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

/* Vetëm përdoruesi mund të modifikojë profilin e tij */
CREATE POLICY "Users can update own profile"
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

/* Vetëm përdoruesi mund të fshijë profilin e tij */
CREATE POLICY "Users can delete own profile"
ON profiles FOR DELETE
TO authenticated
USING (auth.uid() = id);


/* --- B. LISTINGS --- */
/* Shpalljet mund të lexohen nga të gjithë vizitorët */
CREATE POLICY "Listings are viewable by everyone"
ON listings FOR SELECT
USING (true);

/* Vetëm përdoruesit e regjistruar mund të postojnë (dhe seller_id duhet të jetë llogaria e tyre) */
CREATE POLICY "Users can create listings"
ON listings FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = seller_id);

/* Vetëm shitësi që e ka krijuar shpalljen mund ta modifikojë atë */
CREATE POLICY "Users can update own listings"
ON listings FOR UPDATE
TO authenticated
USING (auth.uid() = seller_id)
WITH CHECK (auth.uid() = seller_id);

/* Vetëm shitësi mund ta fshijë shpalljen e tij */
CREATE POLICY "Users can delete own listings"
ON listings FOR DELETE
TO authenticated
USING (auth.uid() = seller_id);


/* --- C. MESSAGES (BISEDAT PRIVATE) --- */
/* Vetëm dërguesi, blerësi i bisedës ose shitësi i shpalljes mund t'i lexojë mesazhet */
CREATE POLICY "Users can view their own messages"
ON messages FOR SELECT
TO authenticated
USING (
  auth.uid() = user_id 
  OR (buyer_id IS NOT NULL AND auth.uid() = buyer_id)
  OR auth.uid() IN (SELECT seller_id FROM listings WHERE id = messages.listing_id)
);

/* Përdoruesi i kyçur mund të dërgojë mesazh vetëm me ID-në e tij */
CREATE POLICY "Users can insert messages"
ON messages FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

/* Përdoruesi mund të fshijë mesazhet e tij ose shitësi mund të pastrojë bisedat në shpalljen e tij */
CREATE POLICY "Users can delete own messages"
ON messages FOR DELETE
TO authenticated
USING (
  auth.uid() = user_id
  OR auth.uid() IN (SELECT seller_id FROM listings WHERE id = messages.listing_id)
);

/* Marrësi i mesazhit ose shitësi i shpalljes mund të përditësojë 'is_read' */
CREATE POLICY "Users can update received messages"
ON messages FOR UPDATE
TO authenticated
USING (
  auth.uid() = user_id
  OR auth.uid() IN (SELECT seller_id FROM listings WHERE id = messages.listing_id)
)
WITH CHECK (
  auth.uid() = user_id
  OR auth.uid() IN (SELECT seller_id FROM listings WHERE id = messages.listing_id)
);


/* --- D. FAVORITES --- */
/* Përdoruesi mund të shohë vetëm postimet e tij të ruajtura */
CREATE POLICY "Users can view own favorites"
ON favorites FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

/* Përdoruesi mund të ruajë shpallje vetëm për llogarinë e tij */
CREATE POLICY "Users can insert own favorites"
ON favorites FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

/* Përdoruesi mund të heqë shpallje nga të ruajturat vetëm për llogarinë e tij */
CREATE POLICY "Users can delete own favorites"
ON favorites FOR DELETE
TO authenticated
USING (auth.uid() = user_id);


/* --- E. SELLER REVIEWS --- */
/* Të gjithë mund të shohin vlerësimet e një shitësi */
CREATE POLICY "Allow all to view reviews"
ON seller_reviews FOR SELECT
USING (true);

/* Përdoruesi mund të vlerësojë vetëm me llogarinë e tij DHE nuk mund të vlerësojë veten */
CREATE POLICY "Allow authenticated to insert reviews"
ON seller_reviews FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = reviewer_id 
  AND auth.uid() <> seller_id
);

/* Përdoruesi mund të fshijë/ndryshojë vetëm vlerësimin e vet */
CREATE POLICY "Users can update own reviews"
ON seller_reviews FOR UPDATE
TO authenticated
USING (auth.uid() = reviewer_id)
WITH CHECK (auth.uid() = reviewer_id);


/* --- F. REPORTS (RAPORTIMET) --- */
/* Përdoruesit mund të dërgojnë raportime (edhe anonimë) */
CREATE POLICY "Allow all to submit reports"
ON reports FOR INSERT
WITH CHECK (true);

/* Raportimet e dërguara NUK mund të lexohen nga klientët publikë (vetëm service_role) */


/* ====================================================================
   5. STORAGE BUCKET SECURITY (Për fotot e shpalljeve)
   ==================================================================== */
/* Krijojmë bucket-in 'images' nëse nuk ekziston */
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

/* Lejo leximin publik të fotove */
DROP POLICY IF EXISTS "Public Access to Images" ON storage.objects;
CREATE POLICY "Public Access to Images"
ON storage.objects FOR SELECT
USING (bucket_id = 'images');

/* Lejo ngarkimin e fotove vetëm nga përdoruesit e kyçur */
DROP POLICY IF EXISTS "Authenticated users can upload images" ON storage.objects;
CREATE POLICY "Authenticated users can upload images"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'images');

/* Lejo fshirjen e fotos nga pronari */
DROP POLICY IF EXISTS "Users can delete own images" ON storage.objects;
CREATE POLICY "Users can delete own images"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'images' AND auth.uid() = owner);


/* ====================================================================
   6. FUNKSIONET RPC, TRIGGERS & INDEKSET E PERFORMANCËS
   ==================================================================== */

/* A. Funksion RPC për të rritur shikimet e shpalljes nga çdo vizitor pa komprometuar sigurinë e shpalljes */
CREATE OR REPLACE FUNCTION public.increment_listing_views(listing_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.listings
  SET views = COALESCE(views, 0) + 1
  WHERE id = listing_id;
END;
$$;

/* B. Krijimi automatik i profilit publik sapo krijohet një llogari e re në auth.users */
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    NULL
  )
  ON CONFLICT (id) DO UPDATE
    SET display_name = EXCLUDED.display_name
    WHERE profiles.display_name IS NULL OR profiles.display_name = '';
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

/* C. Indekset për shpejtësi të lartë kërkimi (Performance Indexes) */
CREATE INDEX IF NOT EXISTS idx_listings_created_at ON public.listings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_listings_seller_id ON public.listings(seller_id);
CREATE INDEX IF NOT EXISTS idx_listings_category ON public.listings(category);
CREATE INDEX IF NOT EXISTS idx_messages_listing_id ON public.messages(listing_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON public.messages(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON public.favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_listing_id ON public.favorites(listing_id);

